# Laboratorio # 5

Vamos a leer el dataset

In [21]:
import pandas as pd


train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [23]:
train.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [24]:
test.head()

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

Vamos a empezar a limpiar el dataset. Primero vamos a convertir todo el texto a minúscula.

In [25]:
import re

def convert_to_lower(word):
    return word.lower()

def remove_special_characters(word):
    return word.replace("#", "").replace("@", "").replace("'", "")

def remove_url(word):
    text = re.sub(r'http\S+|www\S+|https\S+', '', word)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def remove_emojis(word):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticonos 🙂
        "\U0001F300-\U0001F5FF"  # símbolos y pictogramas 🗻
        "\U0001F680-\U0001F6FF"  # transporte y mapas 🚗
        "\U0001F1E0-\U0001F1FF"  # banderas 🇬🇹
        "\U00002700-\U000027BF"  # símbolos varios ➡
        "\U0001F900-\U0001F9FF"  # suplementarios 🤖
        "\U00002600-\U000026FF"  # misceláneos ☀
        "\U00002B00-\U00002BFF"  # flechas ⬆
        "\U0001FA70-\U0001FAFF"  # emojis recientes 🪐
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', word).strip()

train['text'] = train['text'].astype(str).apply(convert_to_lower)
train['text'] = train['text'].astype(str).apply(remove_special_characters)
train['text'] = train['text'].astype(str).apply(remove_url)
train['text'] = train['text'].astype(str).apply(remove_emojis)


train.head()

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this earthquake ma...,1
1,4,NaN,NaN,forest fire near la ronge sask. canada,1
2,5,NaN,NaN,all residents asked to shelter in place are be...,1
3,6,NaN,NaN,"13,000 people receive wildfires evacuation ord...",1
4,7,NaN,NaN,just got sent this photo from ruby alaska as s...,1

## Limpieza
### Quitar los signos de puntuacion

In [26]:
import re

train["text"] = train["text"].str.replace(r'[^\w\s]', '', regex=True)

test["text"] = test["text"].str.replace(r'[^\w\s]', '', regex=True)

### Quitar los artículos, preposiciones y conjunciones

In [27]:
import pandas as pd
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    tokens = text.split()  # separar en palabras
    tokens = [word for word in tokens if word.lower() not in stop_words]
    return " ".join(tokens)

# Aplicar a las columnas
train["text"] = train["text"].apply(remove_stopwords)
test["text"] = test["text"].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ppguz\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

### Quitar numeros

Primero vamos a ver cuales eliminar, listando por los que mas aparecen

In [29]:
import re
import pandas as pd

def extract_numbers(text):
    return re.findall(r'\d+', str(text))
train_nums = train.copy()
train_nums["numbers"] = train_nums["text"].apply(extract_numbers)

test_nums = test.copy()
test_nums["numbers"] = test_nums["text"].apply(extract_numbers)

all_nums = pd.concat([train_nums[["numbers"]], test_nums[["numbers"]]], ignore_index=True)

all_nums = all_nums[all_nums["numbers"].map(len) > 0]

import numpy as np
all_numbers_flat = np.concatenate(all_nums["numbers"].values)

summary = pd.Series(all_numbers_flat).value_counts().reset_index()
summary.columns = ["number", "count"]
summary

     number  count
0         2    641
1         3    504
2         4    468
3         1    462
4         5    461
..      ...    ...
838    1233      1
839     801      1
840     317      1
841    4552      1
842  325000      1

[843 rows x 2 columns]

Sabiendo esto vamos a conservar los numeros 1945, 911, 2008, 2014, 1980, 2013, 2016, 2011  ya que son fechas importantes, ademas de que son numeros de telefono que pueden tener relacion con el analisis de sentimientos

In [30]:
import re

allowed_numbers = {"1945", "911", "2008", "2014", "1980", "2013", "2016", "2011"}

def remove_unwanted_numbers(text):
    return re.sub(r'\b(?!' + '|'.join(allowed_numbers) + r')\d+\b', '', str(text))

train["text"] = train["text"].apply(remove_unwanted_numbers)
test["text"] = test["text"].apply(remove_unwanted_numbers)


test.head()

   id keyword location                                               text
0   0     NaN      NaN                        happened terrible car crash
1   2     NaN      NaN  Heard earthquake different cities stay safe ev...
2   3     NaN      NaN  forest fire spot pond geese fleeing across str...
3   9     NaN      NaN              Apocalypse lighting Spokane wildfires
4  11     NaN      NaN               Typhoon Soudelor kills  China Taiwan

In [34]:
train.head()

,id,keyword,location,text,target
0,1,NaN,NaN,deeds reason earthquake may allah forgive us,1
1,4,NaN,NaN,forest fire near la ronge sask canada,1
2,5,NaN,NaN,residents asked shelter place notified officer...,1
3,6,NaN,NaN,people receive wildfires evacuation orders ca...,1
4,7,NaN,NaN,got sent photo ruby alaska smoke wildfires pou...,1

Ahora vamos a contar las palabras más frecuentes en cada categoría. Primero vamos a empezar con los tweets que si hablan de desastres naturales

In [46]:
from collections import Counter

natural_disaters = train[train['target'] == 1]

def count_words(dataset, column):
    all_words = ''
    for i in dataset[column]:
        all_words = all_words + i + ' '

    all_words = all_words.split()

    frequency = Counter(all_words)

    print("{:<10} {:<10}".format("Palabra", "Frecuencia"))
    print("-" * 20)
    for palabra, freq in frequency.most_common():
        print("{:<10} {:<10}".format(palabra, freq))


count_words(natural_disaters, 'text')

Palabra    Frecuencia
--------------------
fire       178
news       136
via        121
disaster   117
california 111
suicide    110
police     107
amp        106
people     105
killed     93
like       92
hiroshima  86
storm      85
crash      84
fires      84
us         81
families   81
train      79
emergency  76
buildings  75
bomb       74
two        71
mh370      71
nuclear    70
attack     69
video      69
wildfire   69
get        66
accident   66
bombing    66
one        65
northern   64
burning    64
dead       63
pm         62
legionnaires 62
bomber     60
homes      58
car        57
still      57
war        57
im         56
new        56
atomic     56
obama      54
fatal      54
years      53
collapse   51
may        50
forest     50
debris     50
dont       50
watch      50
first      49
japan      49
malaysia   49
man        48
latest     48
mass       48
near       47
rt         47
water      47
severe     47
today      46
earthquake 45
confirmed  45
found      44
oil        44
home       42
army       42
warning    42
city       42
spill      42
floods     42
world      41
injured    41
derailment 41
evacuation 40
wreckage   40
outbreak   40
weather    39
saudi      39
thunderstorm 39
migrants   39
could      38
old        38
flood      37
flooding   37
say        37
missing    37
investigators 37
bridge     36
back       35
suspect    35
state      35
death      35
mosque     35
rescuers   35
island     34
kills      34
would      34
charged    34
wounded    34
area       33
many       33
murder     33
report     33
anniversary 33
hundreds   33
reunion    32
air        32
wild       32
boy        32
another    32
û_         32
lives      32
affected   32
county     31
heat       31
truck      31
day        31
terrorist  31
pkk        31
year       31
drought    31
typhoon    31
detonated  31
school     30
rain       30
live       30
airplane   30
plane      30
officials  30
deaths     30
refugees   30
got        29
damage     29
airport    29
hit        29
since      29
says       29
look       29
time       29
flames     29
evacuated  29
massacre   29
razed      29
go         28
times      28
violent    28
israeli    28
released   28
going      28
turkey     28
evacuate   28
casualties 28
boat       28
calgary    28
survivors  28
terrorism  28
sandstorm  28
16yr       28
update     27
bus        27
explosion  27
know       27
last       27
life       27
india      27
hurricane  27
natural    27
caused     27
hostages   27
sue        27
officer    27
please     26
least      26
attacked   26
said       26
food       26
declares   26
devastation 26
sinkhole   26
failure    26
minute     26
road       25
helicopter 25
august     25
iran       25
mp         25
displaced  25
service    25
collided   25
abc        25
derailed   25
typhoondevastated 25
saipan     25
dust       25
fatalities 25
structural 25
swallowed  25
conclusively 25
due        24
family     24
aircraft   24
issues     24
hail       24
possible   24
group      24
rioting    24
catastrophic 24
collision  24
wind       24
isis       24
projected  24
lightning  24
bestnaijamade 24
see        23
three      23
wave       23
breaking   23
set        23
shooting   23
reuters    23
help       23
u          23
tragedy    23
bigger     23
searching  23
crews      23
signs      23
plan       23
volcano    23
manslaughter 23
la         22
tornado    22
south      22
north      22
traffic    22
right      22
youtube    22
crashed    22
house      22
cause      22
ambulance  22
feared     22
way        22
thats      22
post       22
make       22
soudelor   22
horror     22
famine     22
trench     22
refugio    22
costlier   22
died       21
ûò         21
west       21
past       21
even       21
cant       21
saw        21
amid       21
bioterror  21
security   21
hot        21
land       21
landslide  21
crisis     21
trains     21
rescue     21
memories   21
11yearold  21
bodies     21
street     20
shot       20
black      20
good       20
arson      20
story      20
weapon     20
fedex      20
work       20
think      20
best       20
hope       20
weapons    20
site       20
rescued    20
cyclone    20
thunder    20
hazardous  20
building   19
st         19
shit       19
trauma     19
national   19
looks      19
kill       19
movie      19
power      19
take       19
american   19
village    19
issued     19
saved      19
declaration 19
engulfed   19
picking    19
disea      19
photo      18
heavy      18
getting    18
myanmar    18
flag       18
government 18
call       18
pakistan   18
ok         18
high       18
east       18
christian  18
muslims    18
temple     18
mount      18
youth      18
fukushima  18
lab        18
hostage    18
marks      18
bush       18
military   18
coaches    18
pic        18
murderer   18
rainstorm  18
virgin     18
closed     17
flash      17
theres     17
rd         17
experts    17
little     17
come       17
need       17
theater    17
next       17
media      17
end        17
libya      17
never      17
nagasaki   17
must       17
outrage    17
mph        17
line       17
injuries   17
flight     17
derail     17
madhya     17
pradesh    17
hailstorm  17
hijacker   17
coming     16
far        16
around     16
stop       16
ago        16
wake       16
pakistani  16
services   16
whole      16
really     16
case       16
major      16
called     16
read       16
children   16
fight      16
caught     16
militants  16
bombs      16
inside     16
bombed     16
70th       16
giant      16
houses     16
reports    16
half       16
landing    16
tonight    16
nws        16
hijack     16
galactic   16
cars       15
center     15
great      15
horrible   15
everyone   15
waving     15
pamela     15
geller     15
transport  15
anthrax    15
bioterrorism 15
women      15
every      15
came       15
aug        15
save       15
bbc        15
chemical   15
trapped    15
passengers 15
summer     15
cdt        15
ebola      15
hijacking  15
rly        15
place      14
top        14
lost       14
reported   14
use        14
twelve     14
history    14
river      14
toddler    14
terror     14
longer     14
mishaps    14
nearly     14
firefighters 14
well       14
coast      14
central    14
global     14
collapsed  14
part       14
blast      14
taiwan     14
wreck      14
b          14
survived   14
marians    14
seismic    14
electrocuted 14
crematoria 14
provoke    14
nigerian   14
recount    14
whirlwind  14
across     13
second     13
days       13
huge       13
w          13
n          13
god        13
men        13
change     13
israel     13
red        13
escape     13
russia     13
peace      13
victims    13
white      13
gun        13
udhampur   13
claims     13
went       13
fear       13
thursday   13
without    13
ever       13
nearby     13
town       13
want       13
action     13
casualty   13
russian    13
responders 13
leave      13
disease    13
airlines   13
york       13
much       13
cnn        13
wrought    13
drowned    13
tsunami    13
prebreak   13
reactor    13
alabama    13
quarantined 13
windstorm  13
smoke      12
ablaze     12
outside    12
vehicle    12
scene      12
france     12
early      12
driver     12
survive    12
poor       12
country    12
destroyed  12
arrested   12
big        12
texas      12
run        12
support    12
germs      12
body       12
health     12
away       12
done       12
gunman     12
fall       12
washington 12
cranes     12
following  12
gas        12
china      12
investigating 12
isnt       12
plans      12
order      12
struggles  12
winds      12
former     12
roosevelt  12
eyewitness 12
parole     12
mudslide   12
cameroon   12
ûïwhen     12
plunging   12
expected   11
wildfires  11
gonna      11
others     11
ave        11
climate    11
dies       11
week       11
members    11
wednesday  11
believe    11
victim     11
serious    11
destruction 11
usa        11
palestinian 11
suspected  11
love       11
remember   11
blood      11
thing      11
carrying   11
islamic    11
potus      11
holding    11
sinking    11
destroys   11
downtown   11
express    11
face       11
also       11
japanese   11
heard      11
takes      11
british    11
denver     11
almost     11
send       11
wounds     11
indian     11
morning    11
alarm      11
destroy    11
philippines 11
loud       11
drowning   11
utc20150805 11
islam      11
exploded   11
med        11
governor   11
snowstorm  11
exchanging 11
shots      11
richmond   11
colorado   10
ûó         10
burned     10
thousands  10
something  10
moving     10
left       10
injury     10
happened   10
examining  10
four       10
omg        10
incident   10
crazy      10
didnt      10
actually   10
ap         10
control    10
linked     10
girl       10
heart      10
used       10
free       10
govt       10
woman      10
deal       10
full       10
doesnt     10
cut        10
region     10
id         10
keep       10
cool       10
taken      10
fears      10
event      10
shows      10
watching   10
killing    10
point      10
tell       10
always     10
worst      10
bad        10
made       10
rocky      10
western    10
riot       10
real       10
night      10
hazard     10
someone    10
photos     10
large      10
civilian   10
rise       10
record     10
catastrophe 10
care       10
cliff      10
let        10
buses      10
person     10
danger     10
metro      10
expect     10
daily      10
strong     10
human      10
mediterranean 10
usgs       10
oklahoma   10
hawaii     10
municipal  10
yyc        10
captures   10
sh         10
tree       10
bayelsa    10
grows      10
patience   10
jonathan   10
c130       10
specially  10
modified   10
stadium    10
1980       10
repatriated 10
rubble     10
spaceship  10
orders     9
hwy        9
causes     9
areas      9
america    9
motorcyclist 9
property   9
manchester 9
nc         9
ill        9
french     9
bin        9
worldnews  9
safety     9
annihilation 9
apocalypse 9
child      9
cases      9
crime      9
true       9
stay       9
spos       9
response   9
ca         9
2nd        9
research   9
phone      9
living     9
hours      9
strike     9
soldiers   9
foxnews    9
united     9
main       9
turkish    9
etc        9
camp       9
tomorrow   9
millions   9
youre      9
oh         9
uk         9
gt         9
piece      9
hear       9
lol        9
risk       9
confirms   9
demolished 9
demolition 9
green      9
freak      9
feel       9
truth      9
antioch    9
detonation 9
move       9
sismo      9
time20150806 9
abstorm    9
sick       9
baby       9
canyon     9
tram       9
market     9
fatality   9
allows     9
spring     9
ass        9
canada     8
residents  8
lake       8
office     8
head       8
onto       8
drive      8
begin      8
pilot      8
theyre     8
die        8
laden      8
close      8
couple     8
annihilated 8
ready      8
game       8
thought    8
forecast   8
science    8
bay        8
nyc        8
prepare    8
mumbai     8
training   8
yeah       8
terrorists 8
young      8
public     8
bc         8
using      8
nothing    8
legacy     8
africa     8
taking     8
2013       8
ashes      8
trent      8
twitter    8
situation  8
things     8
literally  8
afternoon  8
business   8
acres      8
told       8
ppl        8
ban        8
afghanistan 8
iraq       8
million    8
sad        8
ocean      8
learning   8
effects    8
bombings   8
moment     8
chicago    8
thanks     8
highway    8
till       8
bicyclist  8
e          8
sea        8
tropical   8
damaged    8
centre     8
ar         8
thunderstorms 8
capsizes   8
related    8
malaysian  8
search     8
content    8
rail       8
helping    8
detonate   8
return     8
genocide   8
internally 8
kids       8
zone       8
5km        8
abandoned  8
advisory   8
ridge      8
map        8
shift      8
edt        8
apc        8
check      8
mediterran 8
brooklyn   8
sunk       8
reason     7
happening  7
ive        7
setting    7
arsonist   7
later      7
deadly     7
goes       7
official   7
runway     7
anyone     7
hell       7
park       7
mountain   7
fast       7
todays     7
students   7
warnings   7
forces     7
yet        7
give       7
act        7
civilians  7
gaza       7
view       7
battle     7
potential  7
problem    7
ship       7
liked      7
running    7
falling    7
bloody     7
wwii       7
guardian   7
pray       7
syria      7
forget     7
whats      7
ur         7
fuck       7
sirens     7
behind     7
several    7
beautiful  7
hand       7
small      7
squad      7
sky        7
brown      7
middle     7
totally    7
un         7
anything   7
insurance  7
result     7
eruption   7
felt       7
units      7
md         7
along      7
continues  7
continue   7
hard       7
broadway   7
trfc       7
i5         7
find       7
avoiding   7
microlight 7
attacks    7
damn       7
migrant    7
911        7
arabia     7
rìunion    7
relatives  7
deluged    7
kidnapped  7
dozens     7
sound      7
wmata      7
instead    7
relief     7
already    7
freakiest  7
el         7
money      7
devastated 7
president  7
force      7
angry      7
township   7
making     7
trees      7
image      7
wall       7
utc        7
information 7
light      7
parleys    7
powerlines 7
lifted     7
faan       7
become     7
vietnam    7
aid        7
put        7
wx         7
waves      7
budget     7
fighting   7
reddit     7
okwx       7
outlook    7
hwo        7
tension    7
pdp        7
parents    7
threatens  7
bang       7
lies       7
pandemonium 7
quarantine 7
stock      7
opens      7
swallows   7
satellite  7
allah      6
shelter    6
front      6
else       6
lane       6
thank      6
dr         6
exit       6
fucking    6
wings      6
mexico     6
including  6
brazil     6
bit        6
drone      6
cop        6
weve       6
humanity   6
hour       6
snow       6
hate       6
kisii      6
alleged    6
calif      6
nashville  6
team       6
trying     6
lot        6
unit       6
tv         6
driving    6
lt         6
fully      6
usatoday   6
yes        6
blaze      6
info       6
wasnt      6
blown      6
though     6
dropped    6
board      6
name       6
ground     6
yrs        6
worry      6
worse      6
toll       6
australia  6
five       6
distance   6
computers  6
currently  6
wont       6
quickly    6
screaming  6
runs       6
upset      6
cops       6
riots      6
burns      6
mad        6
complex    6
sure       6
reduce     6
might      6
number     6
population 6
chance     6
company    6
wow        6
needs      6
industry   6
avoid      6
rock       6
pain       6
learn      6
course     6
forced     6
rains      6
season     6
working    6
blvd       6
estimate   6
mhtw4fnet  6
side       6
aim        6
false      6
rohingya   6
beach      6
hes        6
month      6
maybe      6
data       6
deluge     6
falls      6
enugu      6
calls      6
film       6
dc         6
updates    6
shut       6
wash       6
sounds     6
walk       6
happen     6
desolation 6
phoenix    6
entire     6
cinema     6
lack       6
room       6
london     6
headed     6
app        6
troops     6
va         6
effect     6
wa         6
travel     6
evening    6
fans       6
portland   6
1945       6
guys       6
rocks      6
p          6
account    6
message    6
tracks     6
approaches 6
start      6
storms     6
hellfire   6
criminals  6
sinjar     6
guillermo  6
inundated  6
murdered   6
meltdown   6
executives 6
prosecuted 6
radiation  6
plains     6
chinas     6
gems       6
screams    6
lowndes    6
disrupts   6
siren      6
gunfire    6
copilot    6
beû_       6
hollywood  6
miners     6
twister    6
amsterdam  6
parker     6
alaska     5
hill       5
wait       5
aba        5
alone      5
wife       5
blocked    5
involving  5
i77        5
mile       5
av         5
motorcycle 5
mma        5
turned     5
lanes      5
gov        5
began      5
wtf        5
eyes       5
crashes    5
pilots     5
hospital   5
nine       5
pulls      5
drunk      5
seconds    5
aware      5
gang       5
total      5
salt       5
horse      5
2014       5
shadow     5
short      5
took       5
putin      5
late       5
dogs       5
leader     5
fan        5
date       5
mop        5
bring      5
authorities 5
burn       5
notices    5
hunt       5
failed     5
italy      5
gave       5
palestine  5
theatre    5
share      5
program    5
avalanche  5
general    5
occurred   5
pathogens  5
hearing    5
sir        5
usagov     5
needed     5
preparedness 5
pretty     5
threat     5
ahead      5
bleeding   5
wanted     5
cross      5
dude       5
japans     5
documents  5
idea       5
miles      5
countries  5
target     5
states     5
words      5
among      5
australian 5
long       5
stealing   5
threatening 5
babies     5
grateful   5
apartment  5
meeting    5
different  5
less       5
remains    5
residential 5
dog        5
metal      5
planned    5
mean       5
incredible 5
fine       5
causing    5
port       5
chinese    5
picture    5
safe       5
keeps      5
seems      5
turn       5
smh        5
calling    5
cannot     5
win        5
afghan     5
sees       5
sharp      5
glad       5
warns      5
nuke       5
political  5
repair     5
southern   5
respond    5
cleanup    5
streak     5
wanna      5
gone       5
actions    5
tent       5
track      5
sac        5
fwy        5
delays     5
mansehra   5
curfew     5
seen       5
ten        5
pass       5
maximum    5
delivers   5
level      5
release    5
rises      5
focus      5
minister   5
online     5
interesting 5
low        5
strategy   5
demolish   5
zionist    5
kaduna     5
smithsonian 5
leaving    5
show       5
mt         5
box        5
struck     5
accidents  5
enough     5
desolate   5
route      5
agree      5
ignition   5
knock      5
talk       5
leading    5
plus       5
sittwe     5
conditions 5
visit      5
stories    5
drown      5
gusts      5
sicily     5
users      5
anchorage  5
scared     5
costs      5
department 5
gold       5
ofû_       5
local      5
class      5
warship    5
friday     5
dramatic   5
estimated  5
reno       5
maryland   5
mansion    5
plug       5
christmas  5
flattened  5
started    5
socialnews 5
parts      5
bjp        5
massive    5
boston     5
policy     5
playing    5
break      5
murderous  5
americaûªs 5
funtenna   5
hat        5
silver     5
italian    5
alps       5
lava       5
experiments 5
cancer     5
nytimes    5
pipeline   5
elevated   5
yobe       5
exploration 5
somalia    5
intensity  5
trolley    5
photography 5
nasahurricane 5
unlocked   5
brakes     5
reality    5
rules      5
trouble    5
upheaval   5
pov        5
exchange   5
officers   4
sent       4
rockyfire  4
streets    4
haha       4
flooded    4
florida    4
jamaica    4
santa      4
cruz       4
deputies   4
six        4
church     4
nb         4
owner      4
sunday     4
rider      4
alberta    4
blocking   4
details    4
previously 4
job        4
july       4
insane     4
dtn        4
worried    4
guess      4
arabian    4
hunters    4
syrian     4
sign       4
stand      4
heres      4
begins     4
dad        4
armageddon 4
rally      4
lion       4
pick       4
fake       4
mourning   4
stabbing   4
stir       4
ûpolitics  4
griefûª    4
jewish     4
teen       4
bar        4
tennessee  4
serial     4
newyork    4
demand     4
horrific   4
muslim     4
blasts     4
karachi    4
internet   4
raid       4
homeless   4
prior      4
fact       4
mine       4
student    4
sunset     4
listen     4
radio      4
v          4
star       4
eye        4
stops      4
shipping   4
tcot       4
stopped    4
cdc        4
nasa       4
wht        4
auth       4
blk        4
drill      4
concerned  4
irandeal   4
broken     4
olympic    4
losses     4
double     4
battling   4
refugee    4
hi         4
tho        4
aint       4
deep       4
played     4
fun        4
gets       4
bagging    4
majority   4
jet        4
1st        4
cos        4
harbor     4
forever    4
villages   4
conflict   4
mission    4
months     4
marked     4
australias 4
reminds    4
calamity   4
congress   4
fox        4
businesses 4
matter     4
uganda     4

Ahora vamos con los tweets que no son de desastres naturales

In [45]:
no_natural_disasters = train[train['target'] == 0]
count_words(no_natural_disasters, 'text')

Palabra    Frecuencia
--------------------
like       253
im         243
amp        192
new        168
get        163
dont       141
one        127
body       112
via        99
would      97
video      96
people     91
love       89
know       85
back       84
time       83
us         83
got        83
see        82
cant       81
emergency  81
full       81
day        78
youtube    76
going      75
still      72
fire       72
go         67
want       67
good       67
think      66
man        62
world      62
lol        61
rt         60
life       60
u          59
youre      58
first      58
news       57
last       56
burning    56
really     55
way        55
need       55
make       54
work       54
best       53
let        52
much       51
many       51
even       51
take       50
help       48
say        48
great      47
wreck      47
right      46
feel       46
black      46
content    46
hot        45
look       44
every      44
god        44
never      44
please     44
fear       44
could      43
read       42
ass        42
cross      42
bags       42
ever       41
today      41
night      40
top        40
fucking    40
come       39
bag        39
reddit     39
check      38
year       38
getting    38
everyone   38
hes        38
may        38
without    38
shit       37
another    37
screaming  37
bloody     37
liked      37
ruin       37
panic      37
always     36
ive        36
school     36
well       36
smoke      36
death      36
explode    36
wrecked    36
coming     35
face       35
thats      35
watch      35
bad        35
buildings  35
harm       35
disaster   35
home       34
military   34
crash      34
sinking    34
car        33
dead       33
head       33
better     33
next       33
police     33
also       33
stop       33
armageddon 33
war        33
made       33
loud       33
free       32
ebay       32
gonna      32
show       32
hope       32
fuck       32
fall       32
blew       32
w          32
crush      32
curfew     32
storm      32
screamed   32
traumatised 32
twister    32
blood      31
said       31
little     31
nuclear    31
deluge     31
panicking  31
live       30
someone    30
destroy    30
change     30
attack     30
girl       30
wanna      30
put        30
bleeding   30
game       29
run        29
ill        29
army       29
burned     29
keep       29
song       29
bomb       29
collide    29
survive    29
inundated  29
lava       29
quarantine 29
û_         28
phone      28
services   28
soon       28
movie      28
theres     28
long       28
things     28
flames     28
battle     28
destroyed  28
blazing    28
lets       28
drown      28
blown      28
shoulder   28
catastrophe 28
stock      28
desolation 28
trouble    28
flattened  28
sunk       28
summer     27
looks      27
lot        27
injury     27
real       27
big        27
bagging    27
destruction 27
trapped    27
crushed    27
danger     27
demolish   27
electrocute 27
injuries   27
bang       27
obliterated 27
screams    27
week       26
meltdown   26
thank      26
save       26
away       26
apocalypse 26
years      26
two        26
twitter    26
music      26
cause      26
oh         26
plan       26
obliterate 26
obliteration 26
riot       26
end        25
set        25
thing      25
fun        25
high       25
fan        25
sure       25
reû_       25
whole      25
hazard     25
woman      25
cliff      25
detonate   25
drowning   25
survived   25
mudslide   25
thunder    25
nowplaying 24
heard      24
play       24
heart      24
goes       24
collapse   24
white      24
weapons    24
light      24
exploded   24
pandemonium 24
upheaval   24
weapon     24
around     23
annihilated 23
zone       23
red        23
since      23
id         23
photo      23
sound      23
thought    23
beautiful  23
mass       23
hit        23
yet        23
words      23
blight     23
policy     23
market     23
baby       23
collapsed  23
damage     23
hellfire   23
quarantined 23
whirlwind  23
wounds     23
whats      22
thanks     22
tonight    22
kids       22
gets       22
already    22
something  22
making     22
sirens     22
start      22
tomorrow   22
left       22
guys       22
nothing    22
ur         22
detonation 22
stretcher  22
windstorm  22
cool       21
care       21
happy      21
accident   21
didnt      21
wait       21
came       21
book       21
hey        21
leather    21
makes      21
avalanche  21
finally    21
yes        21
old        21
house      21
trying     21
send       21
job        21
demolished 21
demolition 21
fatality   21
used       20
wont       20
went       20
ball       20
food       20
bar        20
shes       20
part       20
pick       20
family     20
times      20
horrible   20
lightning  20
hell       20
probably   20
stay       20
electrocuted 20
trauma     20
truck      19
aftershock 19
wrong      19
brown      19
jobs       19
call       19
everything 19
bc         19
maybe      19
self       19
data       19
anything   19
feeling    19
space      19
women      19
low        19
find       19
bombed     19
deluged    19
rescue     19
flood      19
mayhem     19
offensive  19
city       18
actually   18
ûò         18
ok         18
hours      18
okay       18
remember   18
person     18
story      18
online     18
cake       18
eyes       18
pretty     18
womens     18
spot       18
chemical   18
derail     18
banned     18
responders 18
natural    18
rescued    18
siren      18
side       17
lord       17
mom        17
done       17
anyone     17
might      17
ambulance  17
sorry      17
seen       17
stand      17
tv         17
business   17
believe    17
team       17
longer     17
doesnt     17
hollywood  17
yeah       17
use        17
money      17
half       17
ladies     17
meek       17
waves      17
collided   17
desolate   17
effect     17
drowned    17
engulfed   17
eyewitness 17
tsunami    17
hijacking  17
hat        17
prebreak   17
landslide  17
ablaze     16
ûó         16
die        16
must       16
river      16
national   16
name       16
class      16
blaze      16
lmao       16
hiring     16
literally  16
favorite   16
looking    16
haha       16
wind       16
blizzard   16
though     16
drake      16
appears    16
breaking   16
listen     16
gbbo       16
fires      16
friends    16
emmerdale  16
quiz       16
hail       16
blast      16
ancient    16
reddits    16
rubble     16
miners     16
fast       15
try        15
awesome    15
leave      15
r          15
tell       15
win        15
guy        15
mode       15
trust      15
hate       15
forest     15
vs         15
radio      15
blue       15
damn       15
attacked   15
needs      15
saw        15
deal       15
star       15
level      15
says       15
pay        15
link       15
fashion    15
theyre     15
days       15
hear       15
watching   15
failure    15
hazardous  15
course     15
floods     15
ignition   15
knock      15
water      15
islam      15
evacuate   15
fatalities 15
led        15
hijacker   15
hostage    15
subreddits 15
snowstorm  15
talk       14
plans      14
wants      14
seeing     14
almost     14
ship       14
past       14
wild       14
earth      14
friend     14
gop        14
men        14
added      14
king       14
playing    14
power      14
eye        14
miss       14
fedex      14
move       14
computers  14
heat       14
follow     14
entire     14
soul       14
aint       14
post       14
train      14
photos     14
tote       14
handbag    14
state      14
health     14
alone      14
rise       14
explosion  14
chance     14
crashed    14
rain       14
likely     14
nearby     14
sinkhole   14
chile      14
outside    13
wanted     13
hard       13
upon       13
dance      13
second     13
thinking   13
career     13
annihilation 13
sign       13
comes      13
reason     13
official   13
bed        13
gt         13
learn      13
beach      13
album      13
playlist   13
niggas     13
tweet      13
pain       13
arent      13
art        13
biggest    13
wounded    13
super      13
wow        13
child      13
road       13
casualty   13
become     13
service    13
angry      13
government 13
download   13
released   13
wonder     13
dust       13
x          13
lamp       13
flooding   13
hurricane  13
unconfirmed 13
neighbours 13
reactor    13
seismic    13
tragedy    13
bring      12
inside     12
secret     12
support    12
tried      12
dog        12
place      12
order      12
join       12
fight      12
film       12
scared     12
totally    12
kill       12
peace      12
wake       12
series     12
latest     12
far        12
nice       12
louis      12
bioterror  12
n          12
hair       12
mad        12
party      12
turn       12
weather    12
date       12
running    12
wedding    12
gave       12
buy        12
broke      12
faux       12
saying     12
sex        12
front      12
else       12
businesses 12
view       12
mop        12
refugees   12
cree       12
famine     12
offroad    12
hijack     12
funtenna   12
rioting    12
structural 12
building   11
st         11
means      11
edm        11
guess      11
daily      11
gtgt       11
sometimes  11
lucky      11
nigga      11
history    11
havent     11
united     11
funny      11
direction  11
arsonist   11
media      11
games      11
crazy      11
august     11
lady       11
enough     11
complete   11
text       11
control    11
couple     11
open       11
dad        11
land       11
purse      11
omg        11
centre     11
insurance  11
sounds     11
wave       11
instead    11
absolutely 11
driving    11
donûªt     11
guide      11
cable      11
arianagrande 11
turned     11
public     11
smaug      11
apollo     11
devastated 11
cat        11
rules      11
fatal      11
gems       11
murderer   11
least      10
michael    10
drive      10
behind     10
petition   10
shall      10
country    10
feat       10
survivors  10
park       10
share      10
jeb        10
birthday   10
started    10
version    10
girls      10
door       10
department 10
ago        10
till       10
working    10
arson      10
truth      10
drink      10
ready      10
group      10
worst      10
answer     10
boy        10
future     10
weekend    10
youll      10
ahead      10
beyond     10
dude       10
bitch      10
glass      10
deep       10
others     10
rock       10
technology 10
rather     10
hasnt      10
handbags   10
tablet     10
straight   10
together   10
update     10
children   10
wish       10
america    10
bush       10
emotional  10
internet   10
worlds     10
room       10
info       10
de         10
deaths     10
break      10
press      10
displaced  10
security   10
evacuation 10
reasons    10
bus        10
hostages   10
injured    10
rainstorm  10
chinas     10
london     9
taking     9
teen       9
sleeping   9
double     9
comment    9
financial  9
moment     9
murder     9
sent       9
episode    9
iran       9
paul       9
wasnt      9
kinda      9
played     9
block      9
mod        9
reading    9
give       9
loved      9
hand       9
sense      9
stage      9
isnt       9
lead       9
round      9
gay        9
sit        9
town       9
ice        9
green      9
terrorism  9
secrets    9
feels      9
happened   9
taken      9
occurred   9
transport  9
usa        9
lab        9
bioterrorism 9
welcome    9
months     9
thousands  9
traffic    9
cold       9
sun        9
lost       9
fantasy    9
giving     9
walking    9
brought    9
morning    9
kindle     9
mean       9
feet       9
tired      9
cover      9
glad       9
limited    9
hobo       9
air        9
middle     9
colour     9
ross       9
yall       9
boat       9
apply      9
ppl        9
property   9
hilarious  9
catastrophic 9
general    9
opening    9
idea       9
test       9
oil        9
either     9
worse      9
fans       9
character  9
pray       9
cyclone    9
texas      9
shape      9
pile       9
selfimage  9
international 9
trump      9
different  9
hobbit     9
devastation 9
planned    9
interesting 9
epicentre  9
screen     9
combo      9
desires    9
violent    9
aba        9
delivers   9
sandstorm  9
tornado    9
metal      8
crying     8
sky        8
season     8
perfect    8
single     8
dnb        8
dream      8
possible   8
lose       8
number     8
easy       8
fact       8
match      8
salt       8
horse      8
books      8
took       8
asked      8
unless     8
beat       8
beyhive    8
directioners 8
build      8
vote       8
hero       8
da         8
court      8
original   8
2014       8
o784       8
involving  8
fleets     8
totaling   8
ships      8
australia  8
climate    8
pic        8
facebook   8
sale       8
guns       8
silver     8
obama      8
word       8
joe        8
hands      8
tears      8
brain      8
line       8
told       8
ones       8
poor       8
found      8
releases   8
amazon     8
walk       8
cook       8
gone       8
standard   8
large      8
somebody   8
gotta      8
mary       8
sitting    8
woke       8
huge       8
terrorist  8
problem    8
shouldnt   8
football   8
tho        8
true       8
stuff      8
social     8
wired      8
fat        8
tickets    8
rate       8
prevent    8
ceo        8
center     8
lil        8
animal     8
thunderstorm 8
takes      8
ask        8
gold       8
justinbieber 8
disney     8
anymore    8
changes    8
hold       8
forever    8
derailed   8
killer     8
isis       8
sensorsenso 8
sensor     8
common     8
access     8
travel     8
mortal     8
kombat     8
camp       8
disco      8
lovely     7
alive      7
site       7
quite      7
due        7
risk       7
issue      7
ir         7
icemoon    7
djicemoon  7
dubstep    7
trapmusic  7
icesû_     7
kick       7
vehicle    7
choice     7
able       7
hour       7
practice   7
across     7
baseball   7
short      7
completely 7
voice      7
died       7
minecraft  7
shot       7
dark       7
based      7
govt       7
reaû_      7
navy       7
owner      7
worry      7
lie        7
shift      7
families   7
total      7
tweets     7
v          7
bet        7
lots       7
worth      7
4x4        7
yo         7
happens    7
son        7
lies       7
special    7
pool       7
writing    7
seek       7
experience 7
agree      7
rn         7
p          7
starts     7
universe   7
max        7
1st        7
kid        7
watched    7
mine       7
stories    7
community  7
county     7
clutch     7
bruh       7
young      7
floor      7
hurts      7
seriously  7
listening  7
hello      7
meet       7
friday     7
wtf        7
seat       7
vuitton    7
four       7
small      7
russian    7
flat       7
amazing    7
pass       7
brother    7
shower     7
ground     7
moon       7
minutes    7
crap       7
mind       7
parents    7
stone      7
account    7
nearly     7
stream     7
companies  7
downtown   7
pop        7
list       7
tongue     7
act        7
mix        7
none       7
dan        7
collision  7
near       7
shares     7
falling    7
di         7
pussy      7
dangerous  7
debate     7
boys       7
wife       7
earlier    7
lives      7
matter     7
signed     7
china      7
evening    7
invoices   7
patience   7
enugu      7
root       7
grill      7
kit        7
gm         7
soundcloud 7
f          7
causing    7
crackdown  7
broad      7
queen      7
dogs       7
sea        7
sad        7
information 7
computer   7
uk         7
quick      7
saturday   7
gun        7
fog        7
remove     7
inundation 7
disneys    7
massacre   7
canaanites 7
syrian     7
animalrescue 7
seeks      7
threat     7
mayan      7
volcano    7
cramer     7
eat        6
girlfriend 6
built      6
gained     6
followers  6
grow       6
weird      6
cruz       6
videos     6
students   6
among      6
knew       6
happen     6
david      6
thomas     6
shooting   6
issues     6
steve      6
cannot     6
dying      6
charity    6
waiting    6
passing    6
mets       6
exactly    6
less       6
2011       6
careful    6
angel      6
mountain   6
imagine    6
indeed     6
youve      6
xbox       6
b          6
entertainment 6
movies     6
toddler    6
prepare    6
lights     6
review     6
shows      6
american   6
ca         6
feminists  6
colorado   6
box        6
sweet      6
fully      6
em         6
ya         6
dc         6
attention  6
wars       6
germs      6
research   6
safety     6
action     6
bro        6
lt3        6
weeks      6
bit        6
blessed    6
broken     6
cute       6
blocked    6
talking    6
loving     6
society    6
program    6
report     6
card       6
cream      6
pm         6
butter     6
ideas      6
leaving    6
pc         6
rip        6
nah        6
wall       6
ah         6
stars      6
pressure   6
shoes      6
supposed   6
club       6
player     6
mini       6
republicans 6
monogram   6
edition    6
readû_     6
satchel    6
case       6
enjoy      6
drinking   6
sports     6
according  6
states     6
saving     6
write      6
spent      6
twice      6
understand 6
cars       6
dr         6
casualties 6
industry   6
joy        6
results    6
three      6
human      6
british    6
area       6
drunk      6
trip       6
ha         6
german     6
rubber     6
sunday     6
force      6
san        6
anti       6
burn       6
honestly   6
question   6
foxtrot    6
gta        6
phoenix    6
tree       6
cry        6
company    6
bear       6
diving     6
mikeparractor 6
usually    6
feed       6
shepherd   6
posts      6
missing    6
conference 6
replace    6
mood       6
loose      6
five       6
tryna      6
felt       6
stuart     6
standuser  6
touch      6
major      6
quote      6
drought    6
tips       6
lake       6
surprise   6
suicide    6
caught     6
california 6
nursing    6
veterans   6
hi         6
tribal     6
wouldnt    6
button     6
parenthood 6
53inch     6
300w       6
curved     6
itunes     6
extreme    6
battlefield 6
moments    6
bayelsa    6
browser    6
arrived    6
board      6
sick       6
chinaûªs   6
insurer    6
igers      6
wonderful  5
doubt      5
mac        5
route      5
month      5
2013       5
cuz        5
father     5
using      5
airplane   5
automatic  5
ny         5
happening  5
ended      5
status     5
education  5
stopped    5
officially 5
whos       5
potus      5
tonto      5
thx        5
false      5
following  5
bob        5
zombie     5
fighting   5
beginning  5
romance    5
ben        5
mining     5
blog       5
luck       5
gods       5
rule       5
letûªs     5
ww1        5
tracks     5
gtgtgt     5
fingers    5
slightly   5
sport      5
mtvhottest 5
jackson    5
leads      5
mido       5
charged    5
add        5
chicagoarea 5
admits     5
scheme     5
somehow    5
patrick    5
driver     5
defense    5
dragon     5
clip       5
external   5
electronic 5
usatoday   5
pathogens  5
anthrax    5
mishaps    5
cut        5
tour       5
covered    5
ugh        5
calories   5
fail       5
huh        5
grade      5
spanish    5
nose       5
written    5
apparently 5
characters 5
called     5
everywhere 5
ray        5
sean       5
jack       5
roads      5
load       5
article    5
wins       5
peanut     5
holy       5
thoughts   5
runs       5
arms       5
williams   5
bb17       5
toilet     5
along      5
hip        5
style      5
north      5
bitches    5
mill       5
window     5
bout       5
firefighter 5
putting    5
calls      5
giant      5
pics       5
irandeal   5
coffee     5
picture    5
fantastic  5
anyway     5
knows      5
impact     5
playoffs   5
bluejays   5
ends       5
throw      5
england    5
greatest   5
babies     5
epic       5
cheese     5
yesterday  5
clothes    5
youd       5
except     5
keeps      5
desire     5
diet       5
ted        5
holiday    5
wet        5
tag        5
aka        5
mother     5
co         5
population 5
canûªt     5
audio      5
brothers   5
seattle    5
manager    5
bride      5
sleep      5
easily     5
vinyl      5
loves      5
ep         5
singing    5
fill       5
simple     5
south      5
rear       5
bought     5
starting   5
vine       5
final      5
decided    5
late       5
judge      5
tom        5
interview  5
af         5
np         5
fish       5
itûªs      5